language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "G+A/6+l+PoiGxXx4hUdf1/RnpK2/2F5vcBmjRWpzMRvA7GP2CRcM6N+jpG1/XB8Ko1d2QP8/hypcA6gHywycFGedWqgg51ol416oZnVwNjFjvDAB0Emh5nadHMA/gfdeMIoyaS1I8KISDReTaw8dygKuGpRdqdcU7EHfHUKBkJY="
    - CXXFLAGS="-Werror"
    - BUILD=~/buildTmp
    - LIBPNG_DOWNLOAD=http://download.sourceforge.net/libpng/libpng-
  matrix:
    - LIBPNG_VERSION=1.2.53
    - LIBPNG_VERSION=1.4.16
    - LIBPNG_VERSION=1.5.22
    - LIBPNG_VERSION=1.6.17
    - LIBPNG_VERSION=1.7.0beta64

matrix:
  allow_failures:
    - env: LIBPNG_VERSION=1.7.0beta64

addons:
  coverity_scan:
    project:
      name: "pngwriter/pngwriter"
      description: "C++ library for creating PNG images"
    notification_email: axel.huebl@plasma.ninja
    build_command_prepend: "cmake $TRAVIS_BUILD_DIR"
    build_command:   "make"
    branch_pattern: coverity_scan

script:
  - cd $BUILD
  - cmake $TRAVIS_BUILD_DIR
  - make
  - sudo make install

before_script:
  - uname -r
  - lsb_release -a
# kick without checking dependencies
  - sudo dpkg -r --force-depends libpng12-dev
  - sudo dpkg -r --force-depends libpng12-0
  - sudo rm -rf /usr/include/libpng12 /urs/include/png*.h /usr/lib/x86_64-linux-gnu/libpng*
#  - sudo apt-get remove -qq libpng12-0 libpng12-0:i386
  - sudo dpkg --get-selections
  - wget "$LIBPNG_DOWNLOAD$LIBPNG_VERSION.tar.xz"
  - tar -xJf libpng-$LIBPNG_VERSION.tar.xz
  - cd libpng-$LIBPNG_VERSION
  - ls
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - sudo find /usr/lib -name 'libpng*'
  - mkdir -p $BUILD

after_script:
  - cp -R $TRAVIS_BUILD_DIR/examples/burro.png .
  - export LD_LIBRARY_PATH=`pwd`:$LD_LIBRARY_PATH
  - ./pngtest
