language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - BUILD=~/buildTmp
    - LIBPNG_DOWNLOAD=http://download.sourceforge.net/libpng/libpng-
  matrix:
    - LIBPNG_VERSION=1.2.51
    - LIBPNG_VERSION=1.4.13
    - LIBPNG_VERSION=1.5.18
    - LIBPNG_VERSION=1.6.10

script:
  - cd $BUILD
  - cmake $TRAVIS_BUILD_DIR
  - make
  - sudo make install

before_script:
  - uname -r
  - lsb_release -a
# just overwrite the existing
#  - sudo apt-get remove -qq libpng12-0 libpng12-0:i386
#  - sudo apt-get install -qq xz-utils
  - sudo dpkg --get-selections
  - wget "$LIBPNG_DOWNLOAD$LIBPNG_VERSION.tar.xz"
  - tar -xJf libpng-$LIBPNG_VERSION.tar.xz
  - cd libpng-$LIBPNG_VERSION
  - ls
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - mkdir -p $BUILD
